image: python:3.10

stages:
  - build
  - test

build:
  stage: build
  script:
    - python -v
    - pip install --upgrade pip
    - pip install -r requirements.txt


test:
  stage: test
  script:
    - pytest -m regression --html=reports/report.html --self-contained-html
  artifacts:
    paths:
      - reports/
    when: always