image: python:3.10

stages:
  - build
  - test

build:
  stage: build
  script:
    - python -V
    - python -m venv venv
    - pip install --upgrade pip
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest -k test_login.py


